# Site settings
title: 刘冉的思、辨、悟
email: liuranball@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Exciting, Innovative and Qualified Software
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.liuranthinking.com" # the base hostname & protocol for your site
google_analytics_key: UA-162716213-1

# Build settings
markdown: kramdown
encoding: utf-8

